-- PROCEDURE: public.add_crash(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, bigint)
-- DROP PROCEDURE IF EXISTS public.add_crash(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, bigint);
CREATE
OR REPLACE PROCEDURE public.add_flight(
    _timestamp date,
    _hex text,
    _ttype text,
    _flight text,
    _alt_baro text,
    _alt_geom text,
    _gs text,
    _track text,
    _baro_rate text,
    _squawk text,
    _emergency text,
    _category text,
    _lat text,
    _lon text,
    _nic text,
    _rc text,
    _seen_pos text,
    _r_dst text,
    _r_dir text,
    _version text,
    _nic_baro text,
    _nac_p text,
    _nac_v text,
    _sil text,
    _sil_type text,
    _gva text,
    _sda text,
    _alert text,
    _spi text,
    _mlat text,
    _tisb text,
    _messages text,
    _seen text,
    _rssi text
) LANGUAGE 'sql' AS $ BODY $
INSERT INTO
    public.flight(
        timestamp,
        hex,
        ttype,
        flight,
        altbaro,
        altgeom,
        gs,
        track,
        barorate,
        squawk,
        emergency,
        category,
        lat,
        lon,
        nic,
        rc,
        seenpos,
        rdst,
        rdir,
        version,
        nicbaro,
        nacp,
        nacv,
        sil,
        siltype,
        gva,
        sda,
        alert,
        spi,
        mlat,
        tisb,
        messages,
        seen,
        rssi
    )
VALUES
    (
       _timestamp,
        _hex,
        _ttype,
        _flight,
        _alt_baro,
        _alt_geom,
        _gs,
        _track,
        _baro_rate,
        _squawk,
        _emergency,
        _category,
        _lat,
        _lon,
        _nic,
        _rc,
        _seen_pos,
        _r_dst,
        _r_dir,
        _version,
        _nic_baro,
        _nac_p,
        _nac_v,
        _sil,
        _sil_type,
        _gva,
        _sda,
        _alert,
        _spi,
        _mlat,
        _tisb,
        _messages,
        _seen,
        _rssi
    ) ON CONFLICT (crash_key) DO NOTHING;

$ BODY $;

ALTER PROCEDURE public.add_crash(
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    bigint
) OWNER TO postgres;